#!$PREFIX/bin/bash

if [ ! -d ~/storage ];
then
  termux-setup-storage
fi

sleep 5

pkg install php-apache -y

rm $PREFIX/etc/apache2/httpd.conf

cp httpd.conf $PREFIX/etc/apache2/

rm $PREFIX/etc/apache2/extra/httpd-ssl.conf

cp httpd-ssl.conf $PREFIX/etc/apache2/extra/

pkg install openssl-tool -y

openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.crt -days 365 -nodes -subj '/CN=localhost'

mv -f server.crt $PREFIX/etc/apache2/

mv -f server.key $PREFIX/etc/apache2/

rm -f $PREFIX/bin/tamp

chmod +x tamp

cp tamp $PREFIX/bin/

pkg install mariadb composer -y

mkdir -p /sdcard/htdocs

cp -n .htaccess /sdcard/htdocs/

php_info='/sdcard/htdocs/phpinfo'
if [ ! -d $php_info ];
then
  mkdir $php_info
  echo "<?php phpinfo(); ?>" > $php_info/index.php
fi

if [ ! -d /sdcard/htdocs/phpmyadmin ];
then
  cd /sdcard/htdocs && composer create-project phpmyadmin/phpmyadmin --stability dev --no-dev
fi

cd ~/tamp && cp -f config.inc.php /sdcard/htdocs/phpmyadmin/config.inc.php

YELLOW='\033[0;33m'
NC='\033[0m' # No Color
echo "TAMP installed sucessfully."
echo "/sdcard/htdocs - is your document directory."
echo "Place your files in /sdcard/htdocs"
echo -e "Run: ${YELLOW}tamp start${NC}"

#tamp-setup
